# permissions for end users to edit secretwatchers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: secretwatcher-editor-role
rules:
- apiGroups:
  - api.caseywylie.io
  resources:
  - secretwatchers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - api.caseywylie.io
  resources:
  - secretwatchers/status
  verbs:
  - get
