# permissions for end users to view secretwatchers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: secretwatcher-viewer-role
rules:
- apiGroups:
  - api.caseywylie.io
  resources:
  - secretwatchers
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - api.caseywylie.io
  resources:
  - secretwatchers/status
  verbs:
  - get
